"""Protocol interfaces for infrastructure components.

These define the contracts that infrastructure implementations must satisfy.
Using typing.Protocol keeps the domain layer free of infrastructure dependencies.
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Protocol

from ncms.domain.models import (
    AccessRecord,
    AgentInfo,
    Entity,
    KnowledgeAnnounce,
    KnowledgeAsk,
    KnowledgeResponse,
    KnowledgeSnapshot,
    Memory,
    Relationship,
    SubscriptionFilter,
)

# ── Storage Sub-Protocols ─────────────────────────────────────────────────


class EntityStore(Protocol):
    """Entity and relationship storage for the knowledge graph."""

    async def save_entity(self, entity: Entity) -> None: ...
    async def get_entity(self, entity_id: str) -> Entity | None: ...
    async def find_entity_by_name(self, name: str) -> Entity | None: ...
    async def list_entities(self, entity_type: str | None = None) -> list[Entity]: ...
    async def save_relationship(self, rel: Relationship) -> None: ...
    async def get_relationships(self, entity_id: str) -> list[Relationship]: ...
    async def link_memory_entity(self, memory_id: str, entity_id: str) -> None: ...
    async def get_memory_entities(self, memory_id: str) -> list[str]: ...


class SnapshotStore(Protocol):
    """Agent snapshot storage for surrogate responses."""

    async def save_snapshot(self, snapshot: KnowledgeSnapshot) -> None: ...
    async def get_latest_snapshot(self, agent_id: str) -> KnowledgeSnapshot | None: ...
    async def delete_snapshot(self, agent_id: str) -> None: ...
    async def get_snapshots_by_domain(self, domain: str) -> list[KnowledgeSnapshot]: ...


class ConsolidationStore(Protocol):
    """Key-value state storage for maintenance tasks."""

    async def get_consolidation_value(self, key: str) -> str | None: ...
    async def set_consolidation_value(self, key: str, value: str) -> None: ...
    async def delete_consolidation_value(self, key: str) -> None: ...


# ── Composite Storage Protocol ────────────────────────────────────────────


class MemoryStore(EntityStore, SnapshotStore, ConsolidationStore, Protocol):
    """Persistent storage for memory records.

    Composes EntityStore, SnapshotStore, and ConsolidationStore with
    core memory CRUD and access logging.
    """

    async def initialize(self) -> None: ...
    async def close(self) -> None: ...
    async def save_memory(self, memory: Memory) -> None: ...
    async def get_memory(self, memory_id: str) -> Memory | None: ...
    async def update_memory(self, memory: Memory) -> None: ...
    async def delete_memory(self, memory_id: str) -> None: ...
    async def list_memories(
        self,
        domain: str | None = None,
        agent_id: str | None = None,
        limit: int = 100,
        since: str | None = None,
        memory_type: str | None = None,
    ) -> list[Memory]: ...
    async def log_access(self, record: AccessRecord) -> None: ...
    async def get_access_times(self, memory_id: str) -> list[float]: ...
    async def count_memories(self) -> int: ...


# ── Search & Graph Protocols ──────────────────────────────────────────────


class IndexEngine(Protocol):
    """Full-text search index for memory retrieval."""

    def initialize(self, path: str | None = None) -> None: ...
    def index_memory(self, memory: Memory) -> None: ...
    def search(self, query: str, limit: int = 50) -> list[tuple[str, float]]: ...
    def remove(self, memory_id: str) -> None: ...


class GraphEngine(Protocol):
    """Knowledge graph for entity/relationship storage and traversal."""

    def add_entity(self, entity: Entity) -> None: ...
    def add_relationship(self, rel: Relationship) -> None: ...
    def find_entity_by_name(self, name: str) -> str | None: ...
    def get_neighbors(
        self, entity_id: str, relation_type: str | None = None, depth: int = 1
    ) -> list[Entity]: ...
    def get_entity_ids_for_memory(self, memory_id: str) -> list[str]: ...
    def get_related_memory_ids(self, entity_ids: list[str], depth: int = 1) -> set[str]: ...
    def link_memory_entity(self, memory_id: str, entity_id: str) -> None: ...
    def entity_count(self) -> int: ...
    def relationship_count(self) -> int: ...
    def clear(self) -> None: ...


# ── Knowledge Bus Protocol ────────────────────────────────────────────────


class KnowledgeBusTransport(Protocol):
    """Transport layer for the Knowledge Bus."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def register_provider(self, agent_id: str, domains: list[str]) -> None: ...
    async def deregister_provider(self, agent_id: str) -> None: ...
    async def update_availability(self, agent_id: str, status: str) -> None: ...
    async def ask(self, ask: KnowledgeAsk) -> str: ...
    async def respond(self, response: KnowledgeResponse) -> None: ...
    async def announce(self, announcement: KnowledgeAnnounce) -> None: ...
    async def subscribe(
        self,
        agent_id: str,
        domains: list[str],
        filter_policy: SubscriptionFilter | None = None,
    ) -> None: ...
    async def get_inbox(self, agent_id: str) -> list[KnowledgeResponse]: ...
    async def get_announcements(self, agent_id: str) -> list[KnowledgeAnnounce]: ...
    async def drain_inbox(self, agent_id: str) -> list[KnowledgeResponse]: ...
    async def drain_announcements(self, agent_id: str) -> list[KnowledgeAnnounce]: ...
    def get_providers_for_domain(self, domain: str) -> list[str]: ...
    def is_agent_online(self, agent_id: str) -> bool: ...
    def get_all_agents(self) -> list[AgentInfo]: ...
    def set_ask_handler(
        self,
        agent_id: str,
        handler: Callable[[KnowledgeAsk], Awaitable[KnowledgeResponse | None]],
    ) -> None: ...
