"""Protocol interfaces for infrastructure components.

These define the contracts that infrastructure implementations must satisfy.
Using typing.Protocol keeps the domain layer free of infrastructure dependencies.
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from ncms.domain.intent import IntentResult

from ncms.domain.models import (
    AccessRecord,
    AgentConfigSnapshot,
    AgentInfo,
    ApprovalDecision,
    BusConversation,
    Document,
    DocumentLink,
    Entity,
    EphemeralEntry,
    GraphEdge,
    GroundingLogEntry,
    GuardrailViolation,
    KnowledgeAnnounce,
    KnowledgeAsk,
    KnowledgeResponse,
    KnowledgeSnapshot,
    LLMCallRecord,
    Memory,
    MemoryNode,
    PendingApproval,
    PipelineEvent,
    Project,
    Relationship,
    ReviewScore,
    SearchLogEntry,
    SubscriptionFilter,
)

# ── Storage Sub-Protocols ─────────────────────────────────────────────────


class EntityStore(Protocol):
    """Entity and relationship storage for the knowledge graph."""

    async def save_entity(self, entity: Entity) -> None: ...
    async def get_entity(self, entity_id: str) -> Entity | None: ...
    async def find_entity_by_name(self, name: str) -> Entity | None: ...
    async def list_entities(self, entity_type: str | None = None) -> list[Entity]: ...
    async def save_relationship(self, rel: Relationship) -> None: ...
    async def get_relationships(self, entity_id: str) -> list[Relationship]: ...
    async def link_memory_entity(self, memory_id: str, entity_id: str) -> None: ...
    async def get_memory_entities(self, memory_id: str) -> list[str]: ...


class SnapshotStore(Protocol):
    """Agent snapshot storage for surrogate responses."""

    async def save_snapshot(self, snapshot: KnowledgeSnapshot) -> None: ...
    async def get_latest_snapshot(self, agent_id: str) -> KnowledgeSnapshot | None: ...
    async def delete_snapshot(self, agent_id: str) -> None: ...
    async def get_snapshots_by_domain(self, domain: str) -> list[KnowledgeSnapshot]: ...


class ConsolidationStore(Protocol):
    """Key-value state storage for maintenance tasks."""

    async def get_consolidation_value(self, key: str) -> str | None: ...
    async def set_consolidation_value(self, key: str, value: str) -> None: ...
    async def delete_consolidation_value(self, key: str) -> None: ...


class MemoryNodeStore(Protocol):
    """HTMG typed node storage (Phase 1 + Phase 2)."""

    async def save_memory_node(self, node: MemoryNode) -> None: ...
    async def get_memory_node(self, node_id: str) -> MemoryNode | None: ...
    async def get_memory_nodes_by_type(self, node_type: str) -> list[MemoryNode]: ...
    async def get_memory_nodes_for_memory(self, memory_id: str) -> list[MemoryNode]: ...
    # Phase 2A: Entity state queries
    async def get_current_entity_states(
        self, entity_id: str, state_key: str,
    ) -> list[MemoryNode]: ...
    async def get_entity_states_by_entity(
        self, entity_id: str,
    ) -> list[MemoryNode]: ...
    async def update_memory_node(self, node: MemoryNode) -> None: ...
    # Phase 2B: Temporal queries
    async def get_current_state(
        self, entity_id: str, state_key: str,
    ) -> MemoryNode | None: ...
    async def get_state_at_time(
        self, entity_id: str, state_key: str, timestamp: str,
    ) -> MemoryNode | None: ...
    async def get_state_changes_since(
        self, timestamp: str,
    ) -> list[MemoryNode]: ...
    async def get_state_history(
        self, entity_id: str, state_key: str,
    ) -> list[MemoryNode]: ...
    # Phase 4: Batch node lookup for intent-aware retrieval
    async def get_memory_nodes_for_memories(
        self, memory_ids: list[str],
    ) -> dict[str, list[MemoryNode]]: ...
    # Phase 3: Episode queries
    async def get_open_episodes(self) -> list[MemoryNode]: ...
    async def get_episode_members(
        self, episode_id: str,
    ) -> list[MemoryNode]: ...
    # Phase 5: Consolidation queries
    async def get_closed_unsummarized_episodes(self) -> list[MemoryNode]: ...
    async def get_entities_with_state_count(
        self, min_count: int,
    ) -> list[tuple[str, int]]: ...
    async def get_abstract_nodes_by_type(
        self, abstract_type: str,
    ) -> list[MemoryNode]: ...


class GraphEdgeStore(Protocol):
    """HTMG typed edge storage (Phase 1)."""

    async def save_graph_edge(self, edge: GraphEdge) -> None: ...
    async def get_graph_edges(
        self, source_id: str, edge_type: str | None = None
    ) -> list[GraphEdge]: ...


class EphemeralStore(Protocol):
    """Short-lived cache for low-admission-score content (Phase 1)."""

    async def save_ephemeral(self, entry: EphemeralEntry) -> None: ...
    async def get_ephemeral(self, entry_id: str) -> EphemeralEntry | None: ...
    async def expire_ephemeral(self) -> int: ...


# ── Composite Storage Protocol ────────────────────────────────────────────


class MemoryStore(
    EntityStore,
    SnapshotStore,
    ConsolidationStore,
    MemoryNodeStore,
    GraphEdgeStore,
    EphemeralStore,
    Protocol,
):
    """Persistent storage for memory records.

    Composes EntityStore, SnapshotStore, and ConsolidationStore with
    core memory CRUD and access logging.
    """

    async def initialize(self) -> None: ...
    async def close(self) -> None: ...
    async def save_memory(self, memory: Memory) -> None: ...
    async def get_memory(self, memory_id: str) -> Memory | None: ...
    async def get_memories_batch(self, memory_ids: list[str]) -> dict[str, Memory]: ...
    async def update_memory(self, memory: Memory) -> None: ...
    async def delete_memory(self, memory_id: str) -> None: ...
    async def list_memories(
        self,
        domain: str | None = None,
        agent_id: str | None = None,
        limit: int = 100,
        since: str | None = None,
        memory_type: str | None = None,
    ) -> list[Memory]: ...
    async def log_access(self, record: AccessRecord) -> None: ...
    async def get_access_times(self, memory_id: str) -> list[float]: ...
    async def get_access_times_batch(
        self, memory_ids: list[str],
    ) -> dict[str, list[float]]: ...
    async def count_memories(self) -> int: ...
    # Phase 9: Access record pruning for active forgetting
    async def prune_access_records(
        self, memory_id: str, max_age_days: int,
    ) -> int: ...
    # Phase 8: Search logging for dream cycle PMI
    async def log_search(self, entry: SearchLogEntry) -> None: ...
    async def get_recent_searches(
        self, limit: int = 100, since: str | None = None,
    ) -> list[SearchLogEntry]: ...
    async def get_search_access_pairs(
        self, since: str | None = None,
    ) -> list[tuple[str, list[str]]]: ...
    # Phase 8: Association strengths (PMI output)
    async def save_association_strength(
        self, entity_id_1: str, entity_id_2: str, strength: float,
    ) -> None: ...
    async def get_association_strengths(
        self,
    ) -> dict[tuple[str, str], float]: ...
    async def get_strong_associations(
        self, min_strength: float = 0.3, limit: int = 50_000,
    ) -> list[tuple[str, str, float]]: ...


# ── Search & Graph Protocols ──────────────────────────────────────────────


class IndexEngine(Protocol):
    """Full-text search index for memory retrieval."""

    def initialize(self, path: str | None = None) -> None: ...
    def index_memory(self, memory: Memory) -> None: ...
    def search(self, query: str, limit: int = 50) -> list[tuple[str, float]]: ...
    def remove(self, memory_id: str) -> None: ...


class IntentClassifier(Protocol):
    """Classifies a search query into one of 7 intent classes.

    The primary implementation uses a BM25 exemplar index.  The domain-layer
    ``classify_intent()`` function serves as a keyword-based fallback.
    """

    def classify(self, query: str) -> IntentResult: ...


class GraphEngine(Protocol):
    """Knowledge graph for entity/relationship storage and traversal."""

    def add_entity(self, entity: Entity) -> None: ...
    def add_relationship(self, rel: Relationship) -> None: ...
    def find_entity_by_name(self, name: str) -> str | None: ...
    def get_neighbors(
        self, entity_id: str, relation_type: str | None = None, depth: int = 1
    ) -> list[Entity]: ...
    def get_entity_ids_for_memory(self, memory_id: str) -> list[str]: ...
    def get_related_memory_ids(self, entity_ids: list[str], depth: int = 1) -> set[str]: ...
    def link_memory_entity(self, memory_id: str, entity_id: str) -> None: ...
    def entity_count(self) -> int: ...
    def relationship_count(self) -> int: ...
    def clear(self) -> None: ...
    # Phase 8: Centrality and entity-memory lookups for dream cycle
    def pagerank(self, alpha: float = 0.85) -> dict[str, float]: ...
    def get_memory_ids_for_entity(self, entity_id: str) -> set[str]: ...
    # Phase 9: Personalized PageRank for query-conditioned graph scoring
    def personalized_pagerank(
        self, seed_entities: dict[str, float],
        alpha: float = 0.85, max_iter: int = 50, tol: float = 1e-6,
    ) -> dict[str, float]: ...


# ── Knowledge Bus Protocol ────────────────────────────────────────────────


class KnowledgeBusTransport(Protocol):
    """Transport layer for the Knowledge Bus."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def register_provider(self, agent_id: str, domains: list[str]) -> None: ...
    async def deregister_provider(self, agent_id: str) -> None: ...
    async def update_availability(self, agent_id: str, status: str) -> None: ...
    async def ask(self, ask: KnowledgeAsk) -> str: ...
    async def respond(self, response: KnowledgeResponse) -> None: ...
    async def announce(self, announcement: KnowledgeAnnounce) -> None: ...
    async def subscribe(
        self,
        agent_id: str,
        domains: list[str],
        filter_policy: SubscriptionFilter | None = None,
    ) -> None: ...
    async def get_inbox(self, agent_id: str) -> list[KnowledgeResponse]: ...
    async def get_announcements(self, agent_id: str) -> list[KnowledgeAnnounce]: ...
    async def drain_inbox(self, agent_id: str) -> list[KnowledgeResponse]: ...
    async def drain_announcements(self, agent_id: str) -> list[KnowledgeAnnounce]: ...
    def get_providers_for_domain(self, domain: str) -> list[str]: ...
    def is_agent_online(self, agent_id: str) -> bool: ...
    def get_all_agents(self) -> list[AgentInfo]: ...
    def set_ask_handler(
        self,
        agent_id: str,
        handler: Callable[[KnowledgeAsk], Awaitable[KnowledgeResponse | None]],
    ) -> None: ...


# ── Document Intelligence Protocol (Phase 2.5) ──────────────────────────


class DocumentStore(Protocol):
    """Persistent storage for projects, documents, reviews, and audit records."""

    # ── Projects ──
    async def save_project(self, project: Project) -> None: ...
    async def get_project(self, project_id: str) -> Project | None: ...
    async def list_projects(
        self, status: str | None = None, limit: int = 50,
    ) -> list[Project]: ...
    async def update_project(self, project: Project) -> None: ...

    # ── Documents ──
    async def save_document(self, doc: Document) -> None: ...
    async def get_document(self, doc_id: str) -> Document | None: ...
    async def list_documents(
        self, project_id: str | None = None, doc_type: str | None = None,
        limit: int = 50,
    ) -> list[Document]: ...
    async def search_documents(
        self, entity: str | None = None, doc_type: str | None = None,
        min_score: int | None = None, limit: int = 50,
    ) -> list[Document]: ...
    async def get_document_versions(self, doc_id: str) -> list[Document]: ...

    # ── Document Links ──
    async def save_document_link(self, link: DocumentLink) -> None: ...
    async def get_document_links(
        self, doc_id: str, direction: str = "both",
    ) -> list[DocumentLink]: ...
    async def get_traceability_chain(self, doc_id: str) -> list[DocumentLink]: ...

    # ── Review Scores ──
    async def save_review_score(self, score: ReviewScore) -> None: ...
    async def get_review_scores(
        self, document_id: str | None = None, project_id: str | None = None,
    ) -> list[ReviewScore]: ...

    # ── Pipeline Events ──
    async def save_pipeline_event(self, event: PipelineEvent) -> None: ...
    async def get_pipeline_events(self, project_id: str) -> list[PipelineEvent]: ...

    # ── Pending Approvals (guardrail gates) ──
    async def create_pending_approval(self, approval: PendingApproval) -> None: ...
    async def get_pending_approval(self, approval_id: str) -> PendingApproval | None: ...
    async def list_pending_approvals(
        self, status: str | None = None, project_id: str | None = None,
    ) -> list[PendingApproval]: ...
    async def decide_approval(
        self, approval_id: str, decision: str, decided_by: str,
        comment: str | None = None,
    ) -> bool: ...

    # ── Audit Records ──
    async def save_approval(self, decision: ApprovalDecision) -> None: ...
    async def save_guardrail_violation(self, violation: GuardrailViolation) -> None: ...
    async def save_grounding_entry(self, entry: GroundingLogEntry) -> None: ...
    async def save_llm_call(self, record: LLMCallRecord) -> None: ...
    async def save_config_snapshot(self, snapshot: AgentConfigSnapshot) -> None: ...
    async def save_bus_conversation(self, convo: BusConversation) -> None: ...
